version: '2'

services:
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - /etc/prometheus:/etc/prometheus
            - /data/prometheus:/data/prometheus
        network_mode: host
    loki:
        image: grafana/loki
        ports:
            - "3100:3100"
        command: --config.file="/etc/loki/local-config.yaml"
        network_mode: host
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        network_mode: host
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
    app:
        image: dotnetapm
        ports:
            - "5000:5000"
        network_mode: host